dist: xenial
language: python
cache: pip
python:
  - "3.7"
env:
  - REQ=""
matrix:
  include:
    - python: "3.6"
      env: REQ="Django>=2.2,<3.0"
    - python: "3.6"
      env: REQ="Django>=3.0,<3.1"
    - python: "3.7"
      env: REQ="Django>=2.2,<3.0"
    - python: "3.7"
      env: REQ="Django>=3.0,<3.1"
    - python: "3.8"
      env: REQ="Django>=2.2,<3.0"
    - python: "3.8"
      env: REQ="Django>=3.0,<3.1"
    - python: "3.8"
      env: REQ="Django>=3.1,<3.2"
install:
  - pip install -U pip setuptools coveralls
  - pip install $REQ
  - pip install --editable .
script: "coverage run --source django_admin_filter/ tests/manage.py test testapp"
after_success:
  - coverage report
  - coveralls
